### ISSUE TITLE
CMake build guilde 

### ISSUE THREAD

**Issue by wolkykim** [wolkykim/qlibc#12]
Is there anyone interested in updating INSTALL.md with information about using CMake on Windows/Mac/Linux for those who are not familiar with it?

**Comment by demitsuri** [comment]
@wolkykim I'll update it after merge `port_windows` into the main branch. Unfortunately windows port is still incomplete (no shared memory and semaphores support yet, tested against MinGW only). I can merge it today in the current state, but I think it's a bad idea. BTW @netpoetica already added some lines here: https://github.com/demitsuri/qlibc/blob/feature/port_windows/INSTALL.md

**Comment by wolkykim** [comment]
The install.md file looks good to me.
How about organize it in this way since some of parts written in cmake
section are common?

Getting source code
Configure
  All platform(Windows/Mac/Unix/Linux)
  Linux and Unix, the traditional way
Build
Test
Install
Uninstall
...

About the window port, I think it's ok to merge it to makn as is if you
think it's reasonably complete. Partial support is fine as long as there's
no defect in working set I think. Wonder why you think it's a bad idea. Any
reason I'm not seeing?

Seungyoung

**Comment by demitsuri** [comment]
I suggest to drop autotools support in the nearest future because we can't support both build systems (autotools and cmake) at the same time. CMake is much generic way to make qlibc cross-platform.

After that we can do something like this:
1. Getting source code
2. Prerequisites
2.1 Supported operating systems
2.2 Supported compilers
2.3 Supported CMake versions
2.3.1 Getting CMake for Debian
2.3.2 Getting CMake for Ubuntu
2.3.3 ....
2.3.4 Compiling CMake from source code (just a link to CMake docs)
3. Build
3.1 Troubleshooting (?)
4. Test
5. Install
6. Uninstall
7. Using in other projects (some stuff for developers)

> About the window port, I think it's ok to merge it to makn as is if you
think it's reasonably complete. Partial support is fine as long as there's
no defect in working set I think. Wonder why you think it's a bad idea. Any
reason I'm not seeing?

I didn't test it against MS VC. I think some features such as pthread locks are unavailable for this compiler. Also I just checked is qlibc compilable against MinGW (It's ok here). That's why we need to write some tests for containers and extensions.

**Comment by wolkykim** [comment]
Yes, we may drop autotool and unity it to cmake in the future but I'd like
to see how it goes for a while. Until we are comfortable doing so I'd like
to keep them both working. Since cmake requires an installation is on many
of o/s distributions yet. It may feel difficult to some people working on
limited environment such as embedded minimal o/s. So it has value in that
way I think but when we make a major change that requires both process get
changed, probably that's the time to best consider.

I like the TOC. Not sure if explaining details of how to get cmake is
necessary. Just mentioning cmake is required would do the jobn. Shorter the
install guide, easier to use. Links to external sites breaks. So I prefer
to avoid external links if possible. Just my way.

Thanks a lot. Looking forward to see the merge!

**Comment by wolkykim** [comment]
any progress?

**Comment by demitsuri** [comment]
This is the current state:

#1. Getting source code
##1.1 License

All of the deliverable code in qLibc has been dedicated to the public domain by the authors. Anyone is free to copy, modify, publish, use, compile, sell, or distribute the original `qLibc` code, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.

```
qLibc

 Copyright (c) 2010-2014 Seungyoung Kim.
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice,
    this list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 POSSIBILITY OF SUCH DAMAGE.

```

##1.2 Downloads

Download the latest qLibc version from [github](https://github.com/wolkykim/qlibc/releases).
You also can checkout the current qLibc source code from its [official repository](https://github.com/wolkykim/qlibc).

#2. Prerequisites
##2.1. Supported operating systems
`qLibc` supports POSIX-compliant operating systems, including Linux and MacOS X. Windows support is experimental (semaphores and shared memory are currently unsupported).

##2.2. Supported compilers
Currently only GCC (MinGW for Windows) is supported.

##2.3. Supported CMake versions
`qLibc` requires CMake 2.8.12.

#3. Build
As far as CMake is a make system used for generating platform-dependent makefiles and workspaces, you can transparently use any of supported native make systems. We suppose you use GNU Make or any other compatible implementation.

For in-source build, assuming you have cloned the source into a folder `qlibc`, you can run the following command:

```
$ cd qlibc && cmake .
```

After that you can use your make system as usual:

```
$ make
```

Also you can do an out-source build by the following command:

``` 
$ cd <make_dir> && cmake <path_to_qlibc_dir>
``` 

#4. Test
```
$ make test
```

#5. Install
This command will install `qLibc` on your system. By default, the directory prefix is "/usr/local" so it will be installed in `/usr/local/include` and `/usr/local/lib`:

```
$ make install
```

This will only install header files and library(archive; static and dynamic) files.
The documentation in the "doc" directory will not be installed, so make a copy of it yourself if you want to keep it.

#6. Uninstall
`qLibc` can be completely removed from the system.

```
$ make uninstall
```

#7. Using in other projects (some stuff for developers)
TBD

**Comment by wolkykim** [comment]
I noticed there's no make target for install, uninstall and distclean(I know this is not generated target by default but something good to have) in cmake generated Makefile?

**Comment by wolkykim** [comment]
I have merged some of your install guide into existing one and releases out 2.2.0 today. Thanks for your help.
