### ISSUE TITLE
Comparing floats

### ISSUE THREAD

**Issue by mwlodarski** [wolkykim/qlibc#18]
I'm thinking about using qunit.h for floating-point calculations.

What do you think about <i>assertion</i> like this

```C
#define ASSERT_EQUAL_FLOAT_TOL(p1, p2, tol) ASSERT( (p1<p2 ? p2-p1 : p1-p2) < tol )
```
that can be used in tests:
```C
TEST("Compare floats") {
  float f1 = 1.000000;
  float f2 = 1.000001;
  ASSERT_EQUAL_FLOAT_TOL(f1, f2, 1.0e-7); // should fail
  ASSERT_EQUAL_FLOAT_TOL(f1, f2, 1.0e-6); // who knows???
  ASSERT_EQUAL_FLOAT_TOL(f1, f2, 1.0e-5); // should pass
}
```

**Comment by wolkykim** [comment]
I think this is a good to have but not must to have thing.
I would put this in the actual test code that uses it rather than in qunit.h
Putting too many of assertions tends to confuse users.
