### ISSUE TITLE
Contradictory licence information

### ISSUE THREAD

**Issue by Leushenko** [wolkykim/qlibc#20]
The .io site says:

> All of the deliverable code in qLibc has been dedicated to the public domain by the authors

However, the readme lists a more restrictive two-clause licence, and refers to the LICENCE file which is a traditional BSD-style licence.
Since the source files themselves also contain the same copyright notice and BSD-style licence, I guess that's the one that was intended to apply. That would mean that the project is *not* in the public domain, and the .io description is inaccurate.

**Comment by kirbyfan64** [comment]
I recently pointed this out, and the created updated the README. The web site is auto-generated from that, so I'm assuming that it just hasn't been re-generated yet.

**Comment by wolkykim** [comment]
Thanks for the info. Basically that's because of my ignorance :)
I've corrected it. I'm closing the ticket now, please feel free to reopen if there's anything else.
