### ISSUE TITLE
Ohu~ the project has got 49 stars as of today. It's like doubled in a night. Thank you all!

### ISSUE THREAD

**Issue by wolkykim** [wolkykim/qlibc#21]
I think it's all of our contributors pleasure seeing the number of star increases~ That pays off the efforts we're putting into this project. It's a great day~

**Comment by kirbyfan64** [comment]
This is partly my fault: http://www.reddit.com/r/programming/comments/2zdcv7/qlibc_like_glib_but_200x_simpler_cleaner_and/. :)

**Comment by wolkykim** [comment]
I've read it throughly and found it's very interesting! Thanks for letting me know that. It's definitely fun and worth to see how other people think about this project. I see all the comments there are very meaningful to this project. why using _t, why call it qlibc? why takes OO concept in C lib with extra pointer overhead? Good questions to myself as well... I found your answers there are very identical to what I'd say. I guess the reason I named this project as qLibc is because I like Q? No serious meaning there as you'd guess. :)
