### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [wolkykim/qlibc#25]
I would like to point out that identifiers like "[`_QLIBC_H`](https://github.com/wolkykim/qlibc/blob/bef840f5e80a36fc93ec1d6040b229988c307fb6/include/qlibc/qlibc.h#L35)" and "[`_QLIST_H`](https://github.com/wolkykim/qlibc/blob/bef840f5e80a36fc93ec1d6040b229988c307fb6/include/qlibc/containers/qlist.h#L35)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by wolkykim** [comment]
good point. we can address it.

**Comment by wolkykim** [comment]
I took care of it. It's in develop branch now.
5fb937b593f63f4af6b8f97065703350d73932cf

**Comment by elfring** [comment]
How do you think about to make [your include guards](https://en.wikipedia.org/wiki/Include_guard#Difficulties "Consistency for include guards") not only standard-compliant but also really unique by appending [a kind of UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier "universally unique identifier")?

**Comment by wolkykim** [comment]
Something like QLIBC_H_a5fbf873464de?
Is there any reason you're asking this? Is it something your project needs
to meet? Or just a suggestion?

I think this Qbrabra_H style is practically unique enough but sure we can
consider if there's a good reason for that. But for now I'm not quiet sure
if that's good idea.

Seungyoung

**Comment by elfring** [comment]
It is a suggestion. - Would you like to reduce the probability for name clashes a bit more?

**Comment by kirbyfan64** [comment]
If someone's using two libraries named `qlibc`, they probably have enough other scoping issues already.

**Comment by darkdh** [comment]
@elfring I think the header naming is unique enough. Unless you can give us the real example of name collision you encountered or I think this is no big deal.

**Comment by wolkykim** [comment]
For now I am closing this issue. For the addition of uuid can be discussed is another issue if needed. Thank you.
