### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [wolkykim/qlibc#26]
[An extra null pointer check is not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for NULL before free(p)?") in functions like the following.
* [qhashtbl](https://github.com/wolkykim/qlibc/blob/485f2974e557e31dea10409cdaf5e08b97637599/src/containers/qhashtbl.c#L131 "Initialize hash table.")
* [qparse_queries](https://github.com/wolkykim/qlibc/blob/9b5bd253a64c981da5638550bcc9a7237f7bad2f/src/utilities/qencode.c#L41 "Parse URL encoded query string.")

Would you like to apply the following [semantic patch](http://coccinelle.lip6.fr/ "Program transformation with Coccinelle?") to find more update candidates?
```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (x)
    free(x);
```

**Comment by wolkykim** [comment]
Right, free() does nothing when x is NULL. That part of code is more about readability for developers, when I use if(x)free(x) then, at that point x could be null or assigned. when it's just free(x), then it means x must be assigned at that point. so it's like assert(x!=NULL); free(x).

But we can address it. Would you like tosend a pull request?

**Comment by wolkykim** [comment]
Thank you. I've addressed the issue.

**Comment by wolkykim** [comment]
(Oh commit auto closed the issue, I'm reopening)

Yes I'd like to run the semantic patch. Could you do it for me and drop me the output?

**Comment by wolkykim** [comment]
Please reopen the issue or cut another when further addressing is needed.
