### ISSUE TITLE
A comment to the questions about qLibc.

### ISSUE THREAD

**Issue by wolkykim** [wolkykim/qlibc#28]
There's an interesting conversation going on about qLibc. I left below comments at the forum. I'm copying it here for those who might have similar questions.

The full conversation can be seen at [here](http://www.reddit.com/r/programming/comments/2zdcv7/qlibc_like_glib_but_200x_simpler_cleaner_and/)

--

Hi,

I'm the author of qLibc. One of our contributors let me know this interesting conversation is going on here. I've read all thoroughly and I consider all the comments here are so helpful and valuable. Thank you for all the inputs. I will use your input for the future improvements. Just wanted to leave my takeouts and current plan on your suggestions and comments.

## About pointer function approach to the container functions.

* The intention of this approach is to easily switch containers from one to the other with minimizing the need of user code changes. qLibc try to keep the container API similar as much as possible. For an example, switching from hash table to linked-list table or tree table(in dev mode) could be done with one line change. qhashtbl_t *tbl = qhashtbl() => qlisttbl_t *tbl = qlisttbl() then rest of code will work since tbl->put() will work on both containers. (this is not always true but trying to practically make it easier enough for the common parts such as put, get, delete, clear, size, free)

*  I caught this approach from Berkeley DB implementation long time ago. But as you mention here, it carries small overhead. So it has good and bad depends on your perspective and use cases. Personally, I don't think this would be a deal breaker and compromising too much and quiet not sure if it does produce noticeable performance degradation in practice.

* But, besides my personal preference, after all, this is your library, I'm considering to make qLibc provide both traditional APIs and current encapsulated APIs. For an example: qhashtbl_get(tbl, "score") tbl->get(tbl, "score")

* Currently qLibc is adding Left-Leaning Red-Black BST algorithm and will be available soon with a name of qtreetbl. I think this qtreetbl will be the first container providing the both ways then we can expand it to other containers.

## About the name qLibc.

In the history, the many parts of qLibc code has delivered from the successor project of qDecoder. qDecoder is a C library for Common Gateway Interface(CGI). Around 2010, one of qDecoder fan suggested to break the project into 2 parts and maintain the general codes in a separate project. I took the advice then qLibc was born like that. There's qHttpd project which was also departed from qDecoder project. So I gave qLibc a sibling mark of alphabet Q :) I was little concerning about the look similarity between qlibc and glibc in lower case writings. But it just went like that and I like the name. So alphabet Q happened to get a meaning to me. I guess now you all like the name like I do ? Still no? Oh man! I'm sad then...

## qLibc VS. glib?

I think the principals are different. To me glib is like Home Depot. qLibc is like Ace Hardware Store or Radio Shark. qLibc takes practical needs. For an example,

* all the containers and extensions are implemented in 2 files per each. 1 header file and 1 code file. If you need modification to take care of your special need or If you want to use only some part of library or whatever reason, you can merge it into user project by dropping those 2 files.

* Containers takes string type keys in the default put/get API for practical reason and provide binary type key type which is less frequently used in general with little longer method names. It carries convenient wrapper methods by default like putstr which stores string type data and which is technically not necessary once it provides binary key/data pair functionality, all those can be handled in user space. But because it's C, not any other OO languages which is relative simpler to manage user wrappers, it takes more elbow grease, so qLibc carries them. glib's kind of spirit perspective or from standard perspective, it's too kind thing and wouldn't allow it. But qLibc is written to be practical, so it's absolutely ok with qLibc if that's a way we commonly use.

* qLibc is unique and flexibility to adopt the boundary areas. For example, qhasharr which implements hash table in a fixed memory block for shared memory/disk operation has a unique algorithm. It implements Token Bucket, Configuration file parser for apache httpd style configuration, light weight HTTP client since we have great curl library, all the handy hash algorithms including Murmur Hash and FNV. So it's like that, it also provides MD5 hash as well but if your application seriously use MD5(like updating the digest on the fly before finalization), I recommend to use openssl's API since it comes with most of distributions. But if you just need to fingerprint some strings or files, I think using qLibc's API will greatly reduce your efforts on the code. So I think the values of qLibc are there.

* More freedom? 2-clause BSD license vs LGPL license. qLibc, every single line has written from ground up. And as a copyright holder, I can tell all I want is giving back(if I can) what I got from the spirit of opensource.

* And maybe compact, zero dependency, consistent APIs, supports of Windows are +1?

## About using _t suffix that's reserved.

* This is basically because of my ignorance. I knew that recently. The reason I put _t for the object is to help users to identify and treat the returned data structure as an object. It's like saying that accessing the object's internal directly is not intended by the implementation.

* POSIX standard reserves _t to prevent possible name conflicts with user codes. After I knew that fact, I was considering alternatives like _o, _obj, _x, _q or no sufixes but I ended up using qXXX_t notation thinking that using _t sufix would deliver the intended meaning clearly to people's common sense.

* If this is a serious deal breaker then I think it should change but quiet not sure for now. There's some of code standard compliant requests from users and it's going on now but _t suffix is not considered yet and open to hearing.

## Using boolean type, C99

Personally, I say personally, sticking on traditional C coding standard gives pros and cons. With traditional style, your code can be more widely ported with minimum efforts. If I were working on glib, I'd stick to it. For qLibc? I've choose to take the advantages. Using pointer member concept is one of them. Integer type could replace boolean type, or char type could be used for it, but to me it is not obvious not to use boolean type since most of recent dev environments can handle them. C99 makes code more readable, less buggy and I think it helps making the code easier to maintain.

## It's open to all

The project is open to suggestions and looking for better ways all the times. Your interests feeds the project and drives the projects. So drop it a line at the project home if you have any ideas or suggestions. The spirit of open source.

Thank you again for all your interests and valuable comments/suggestions.

Seungyoung “Steve” Kim

# Performance benchmark: encapsulation call VS. direct call.

For those, who's interested in to see the performance diff between encapsulation call VS direct call.

	Test qtreetbl.c
	======================================================================
	* TEST : Test growth of tree 
		                            E 
		          C `````````````````````````````````` R 
		 B ```````````````` D                 N ```````````````` X 
	   [A]````````           ````````       [I]````````        [S]````````   
	   ````       ````      ````   

		   Tree Info : #nodes=10, #red=3, #black=-7, root=E
	.................... OK (20 assertions, 80us)
	* TEST : Test basic but complete .............................. OK (33 assertions, 9us)
	* TEST : Test encapsulated call perf - 1,000,000,000 times  OK (0 assertions, 1592006us)
	* TEST : Test direct call perf - 1,000,000,000 times  OK (0 assertions, 1557411us)

Here the test code:

	TEST("Test encapsulated call perf - 1,000,000,000 times") {
	    qtreetbl_t *tbl = qtreetbl(0);
	    long i;
	    for (i = 0; i < 1000000000; i++) {
		tbl->size(tbl);
	    }
	    tbl->free(tbl);
	}

	TEST("Test direct call perf - 1,000,000,000 times") {
	    qtreetbl_t *tbl = qtreetbl(0);
	    long i;
	    for (i = 0; i < 1000000000; i++) {
		qtreetbl_size(tbl);
	    }
	    tbl->free(tbl);
	}

My dev box has Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz

**Comment by kirbyfan64** [comment]
You mean glib, not glibc, right? Glib is the C utility library with everything but the kitchen sink. Glibc is the GNU implementation of the C standard library.

**Comment by wolkykim** [comment]
Oh yeah, right :)
