### ISSUE TITLE
A new container in  Tree data structure is written and under your review.

### ISSUE THREAD

**Issue by wolkykim** [wolkykim/qlibc#30]
I'm so excited to tell everyone that we're going to add a new container in tree data structure.
That has been wanted for long time. This implementation takes left-leaning red-black BST algorithm and fully written from ground up.

40402e8f02da1c56aa1e9b6611b2698fbe6c7a8c

The implementation adds some useful addition algorithm tune ups such as iteration over LLRB tree and find_nearest_key.

The code might be little rough but I'd like ask your review and feedback and I'll keep working on code polishing.

Thank you all.

**Comment by kirbyfan64** [comment]
Looks neat! However...

...in C++, to avoid re-traversing the entire tree structure over and over again, you can give the `remove` functions an iterator. Could this be added to the qlibc data structures?

**Comment by wolkykim** [comment]
In self-balancing tree like red-black or AVL... it doesn't give any advantages because when an object gets deleted, there's a a few of corresponding rotations to rebalance the tree and during this rotation process the surrounding nodes go up and down. So keeping the last object deleted doesn't cut the cost of multiple object deletion.

Lookup cost is cheap as O(log n), it doesn't have to travel the entire tree structure, it is binary tree. So looking up for the next object to delete from the beginning is actually cheaper than any sort of iteration approach since the tree balances itself continuously on every insert/delete.

**Comment by kirbyfan64** [comment]
I know, but I'm referring to those cases when you're going through a 200,000-element hash table/binary tree one part at a time to find a particular element to delete based on some random attribute. In that case, there isn't even much of a choice, because key-based lookup doesn't work. Example:

```c++
struct MyType { int val; };
std::map<string, MyType> m;
// fill m
int x = 99999;
for (int n=0; n<99999; ++n) m[std::to_string(x--)] = MyType{n+2};
// erase element for which MyType.val is 20
m.erase(std::find_if(m.begin(), m.end(), [](std::pair<string, MyType> p) { return p.value == 20; }));
```

**Comment by wolkykim** [comment]
I see the point. Deletion on the fly during iterating the balanced tree is
tricky. BTW, is there any implementation in balances trees that allows
deletion while iterating objects?

I guess normally it needs to combine 2 containers and use one as a indexer
to avoid that busy stuff. Or dividing identification scan and batch
deletion.

Anyway from library feature perspective I think it's is good to have. I get
an idea and it might be possible but in order to get it done, nodes need to
manage their parent link. That would adds little extra cost from other
operations but it will allow deletion on the way travel.

If you know any reference, let me know.

**Comment by kirbyfan64** [comment]
@wolkykim The C++ set and map classes are implemented using binary trees, but erasing elements with them will invalidate all iterators. I don't think *anything* allows you to quite do that. I'm just referring to the ability to use an iterator as an "index" of sorts.

**Comment by wolkykim** [comment]
Yeah, I hear you. I think tree needs to provide a separate deletion api that takes iterator variable something like:

while(obj = iteration(obj)) {
    if(condition) iteration_delete(obj);
}

Tree implementation that keeps parent link in each node probably is easier to make this by moving iterator to the next element then remove old one. But one of advantage of LLRB algorithm is it doesn't have to manage parent link. It's one of benefits. Making parent link and keep them in rotations are not an issue but once it does it it becomes kind of little weired LLRB implementation. :) Which I don't care really much :)

I know you're not referring that particular case, this looks like
"above iteration delete approach VS. logical approach like below.".

while(obj = iteration(obj)) {
    if(condition) push_to_queue(obj.key);
}
while(key = pop_from_queue) {
    delete_from_tree(key);
}

This is a good item to think about.

**Comment by wolkykim** [comment]
@kirbyfan64 Hey Ryan, you'll like this! Check it out~

**Comment by kirbyfan64** [comment]
:thumbsup

**Comment by kirbyfan64** [comment]
:thumbsup:
