### ISSUE TITLE
about gitignore?

### ISSUE THREAD

**Issue by Charles0429** [wolkykim/qlibc#34]
When I compile and install qlibc, the following files are not ignored to be tracked.
```
# On branch master
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	../lib/libqlibc.so
#	../lib/libqlibc.so.2
#	../lib/libqlibcext.so
#	../lib/libqlibcext.so.2
#	test_qhasharr
#	test_qhasharr_darkdh
#	test_qhashtbl
#	test_qstring
#	test_qtreetbl
nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by wolkykim** [comment]
It is normal. If you don't like it then run "make distclean" command. It will remove those generated files and bring it back to the original distribution state.

**Comment by Charles0429** [comment]
OK, Could these types of files be added into .gitignore?

**Comment by wolkykim** [comment]
then we have to manage it whenever changes are made? Don't you use "git add -u"? but I'm open to pull request.

**Comment by Charles0429** [comment]
Maybe we can use regex, for example

```
tests/^test[^\.]*$
lib/*.so*
```

**Comment by wolkykim** [comment]
looks good to me. Would you like to send a the pull request for that?

**Comment by wolkykim** [comment]
Seems we have .gitignore already ^^; looks netpoetica made it.
I guess you could improve it if you want.

**Comment by wolkykim** [comment]
I just went ahead and changed it. Thanks~ Please feel free to update it.

**Comment by wolkykim** [comment]
@Charles0429 I really appreciate your contribution. Next time you hit any idea to improve any part of the project, just send me a pull request. I'm very much open to it. You know, faster, easier :) Thank you. You have a great weekend!
