### ISSUE TITLE
Confusions on qvector

### ISSUE THREAD

**Issue by Charles0429** [wolkykim/qlibc#41]
- qvector does not provide get method to access a single element
- qvector is based on qlist, which does not provide O(1) time to access elements

In my opinion, I think qvector needs to be implemented based on array, and provide get methods to access element by index.

**Comment by wolkykim** [comment]
Yes, right. qVector is based on linked-list implementation to avoid the array reallocation. There was another person pointing this to me. Maybe we should rename it to like qgrowable. I can see where the confusion come from. We can certainly have an array based vector with an index table on the beginning. A good item for the dev backlog.

**Comment by Charles0429** [comment]
Then do we need to develop an array based vector?

**Comment by wolkykim** [comment]
Yes, if there are demands about it then why not :) Are you interested in?

**Comment by Charles0429** [comment]
Yes, I can try to write one. Do we rename the current `qvector` to `qgrowtable`?

**Comment by wolkykim** [comment]
Sounds good to me. I think we can just drop the current version and replace
with a new one when it's ready.

**Comment by Charles0429** [comment]
OK

**Comment by kirbyfan64** [comment]
@wolkykim You might want to see [this](https://www.youtube.com/watch?v=YQs6IC-vgmo). It's a short, <10 minute video by Bjarne Stroustrup (creator of C++) that shows that, in the real world, linked lists tend to be slower than vectors, even with the extra re-allocations, because there are less cache misses.

**Comment by wolkykim** [comment]
@kirbyfan64 Interesting. Something very good to know. Thanks. Good news is Charles is working on this :)

**Comment by Charles0429** [comment]
@wolkykim Because the new qvector is based on array, so it does not provide interface `addstrf`, which is needed by function `sendrequest` in file `extensions/qhttpclient.c`. I think it might need to modify the code of function `sendrequest`.

**Comment by wolkykim** [comment]
Are you thinking of fixed size objects? Or will it support various size of
objects?

**Comment by Charles0429** [comment]
Yes, it is fixed size objects. It can support various size of object by using objects such as `qstring_t`. It behaves  very similar to STL vector, for example, in vector<string>, the stored objects in vector are pointers to string objects, which does not store the string objects itself.

**Comment by wolkykim** [comment]
Ok, sounds good to me.

**Comment by Charles0429** [comment]
OK, please help modify function `sendrequest` (do we provide adstrf in `qlist_t`?), Thank you:)

**Comment by wolkykim** [comment]
Let's rename it to qgrow for now and we decide whether to drop it or leave it after your code is done so we can better see if qgrow still make sense or not.

**Comment by Charles0429** [comment]
OK
