### ISSUE TITLE
Move `#include <sys/types.h>` to header files

### ISSUE THREAD

**Issue by alexandrelucchesi** [wolkykim/qlibc#48]
I'm getting some errors regarding the types `ssize_t` and `off_t` when including `utilities/qhash.h` in Ubuntu + gcc. Shouldn't the `#include <sys/types.h>` present in `src/utilities/qhash.c` be in the corresponding .h? It fixes the problem...

It also occurs in other files. Following is the output of running `grep "sys/types.h" -R include/ src/`:
```
src/extensions/qhttpclient.c:#include <sys/types.h>
src/utilities/qfile.c:#include <sys/types.h>
src/utilities/qcount.c:#include <sys/types.h>
src/utilities/qhash.c:#include <sys/types.h>
src/internal/md5/md5c.c:#include <sys/types.h>

**Comment by wolkykim** [comment]
Hi, you can just include "qlibc.h" rather than including the individual header files. Anyway the fix is on the way. Thanks.
