### ISSUE TITLE
man page - what man page!

### ISSUE THREAD

**Issue by SlySven** [wolkykim/qlibc#56]
Um, I've just cloned and built this library and I can see there is a `doc` directory and that it contains `html` pages but that these are not _installed_ outside of the source tree. I am intending to use this for a INI config file reader/writer provided by the Extension API on a Raspberry Pi (for a Home Automation Project) that I am `SSH`ing into and I'm not using a GUI so I'd be looking to use `man` (or the GNU preferred documentation `info` system) to browse the reference documentation.

Is it intended to expand the documentation into other formats or to install the information into a known location? :grinning:

**Comment by SlySven** [comment]
Having looked through the existing documentation for the bit I am interested in, I now can see that there is only a reader/parser of config files but there is ___not something that can write it back out to the original file!___ Oh dear. :disappointed:

**Comment by wolkykim** [comment]
Yes, it only provides a parser. And the API documentation in the package is in HTML format for your copy. You can browse them at http://wolkykim.github.io/qlibc/doc/html/files.html
