### ISSUE TITLE
Problem with qstrreplace()

### ISSUE THREAD

**Issue by darkstar999** [wolkykim/qlibc#57]
I use it to replace space in a exec string and it fails. The string was something like "/home/user/test/project/progs/cprogs/this is.sh"  and the function destroys the string. If I use the function for "this is.sh" everything is right.  I try to replace the " " with "\\ " to escape the space for exec.

**Comment by wolkykim** [comment]
Can you provide the code?

**Comment by wolkykim** [comment]
Ping. I don't hear back from you. Closing for now. Please re-open ticket if you believe the problem is from qlibc.
