### ISSUE TITLE
qconfig_parse_file() input crashes

### ISSUE THREAD

**Issue by rwhitworth** [wolkykim/qlibc#61]
Hello,
I was using American Fuzzy Lop (afl-fuzz) to fuzz the input to the `examples/config` program.  It uses the qconfig_parse_file() function that crashes the program if provided certain input.  Is fixing these crashes something you're interested in?  The input files can be found here: https://github.com/rwhitworth/qlibc-fuzz/

**Comment by wolkykim** [comment]
Definitely, where is the config you used? I couldn't find it. Can you post
the config here?

**Comment by rwhitworth** [comment]
The config files are all within the linked repo.  Here is a 'raw' download link to one of them: https://raw.githubusercontent.com/rwhitworth/qlibc-fuzz/master/config/id%3A000000%2Csig%3A11%2Csrc%3A000199%2Cop%3Ahavoc%2Crep%3A16

Note that many of the files contain binary data so copy and pasting them will destroy the test case.  These were named differently when being used by the `examples/config` program, as it hard codes the input filename.

**Comment by wolkykim** [comment]
Fix is in place.
https://github.com/wolkykim/qlibc/commit/1772a2b16f971c4d903f4601773f59cf2c2d1186
Thank you

**Comment by rwhitworth** [comment]
Thanks!
