### ISSUE TITLE
After ./configure, should these files be ignored or committed back?

### ISSUE THREAD

**Issue by netpoetica** [wolkykim/qlibc#8]
After running configure, some files appear in the repo to be modified but without any actual difference in a git diff. It is strange because these files appear as "Untracked", but they existed in the repo right after pulling - for example, Makefile. Additionally, even after running `make clean` these files are still modified. 

What is the suggested method of keeping the repo clean for committing changes upstream for a pull request?

```
➜  qlibc git:(master) ✗ git st
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Makefile
	config.h
	config.log
	config.status
	examples/Makefile
	src/Makefile
	tests/Makefile
```

**Comment by demitsuri** [comment]
Qlibc doesn't use those files. I think all of them will be removed in the future versions of the library.

**Comment by netpoetica** [comment]
Yah it looks like they are just from stuff generated by CMake - adding them to the gitignore will ensure that contributors won't accidentally try to commit them upstream from their fork - do you think this pull request will solve this problem or be helpful?

**Comment by demitsuri** [comment]
Initially qlibc used GNU autotools (I'm not sure, but it seems to be right), but a few time age I proposed to use CMake to support Windows/MacOS X (and other unixes) the most consistent way. So, config.log and other files are artifacts generated by GNU autotools.

I think your contribution is very helpful as long as configure script is used. 
Please don't hesitate to do a contributon again :+1:

**Comment by wolkykim** [comment]
"make distclean" will clean that out.
