### ISSUE TITLE
error: too many arguments to function 'mkdir'

### ISSUE THREAD

**Issue by shlwapi** [wolkykim/qlibc#82]
It's in qfile.c and I'm on MSYS2 with cmake and ninja. Compiler is mingw-w64-x86_64-gcc. POSIX mkdir takes two arguments but Windows' mkdir only take just one. It seems your library doesn't support Windows, isn't it?

**Comment by wolkykim** [comment]
qLibc wasn't designed in mind of supporting Windows and no one with Windows expertise have volunteers yet to make it work on Widnows.
