### ISSUE TITLE
This library is not portable!

### ISSUE THREAD

**Issue by shlwapi** [wolkykim/qlibc#83]
It doesn't use standard C headers but relying on platform specific headers too much. This would work on posix systems but on Windows it's problematic. For example, on mingw64 there is no such header as <sys/sem.h>. It also uses <sys/types.h> that causes problem on mingw64 because on mingw64 there is no such thing as u_int32_t defined. There are ifdefs on source code to check for _WIN32 but I don't think it could build out of the box with MSVC either. This library shouldn't be used if you want something truly portable. There are much better solutions: https://github.com/oz123/awesome-c#frameworks

**Comment by wolkykim** [comment]
qLibc wasn't designed in mind of supporting Windows and no one with Windows expertise have volunteers yet to make it work on Windows.

**Comment by michaellilltokiwa** [comment]
@wolkykim Imho it would be good to state this in the readme because I think a lot of people might be wondering about platform support.
