### ISSUE TITLE
test_qtreetbl.c will segfault with gcc >= 10

### ISSUE THREAD

**Issue by Fullaxx** [wolkykim/qlibc#94]
make test will fail when qlibc is compiled with gcc >= 10.
Under this case, test_qtreetbl.c will compile but will segfault during execution.
I believe that it is caused by the unused `return true;` of drawtree().
[test_qtreetbl_gcc10.txt](https://github.com/wolkykim/qlibc/files/9937114/test_qtreetbl_gcc10.txt)
[test_qtreetbl_gcc11.txt](https://github.com/wolkykim/qlibc/files/9937115/test_qtreetbl_gcc11.txt)
[test_qtreetbl_gcc12.txt](https://github.com/wolkykim/qlibc/files/9937116/test_qtreetbl_gcc12.txt)

**Comment by Fullaxx** [comment]
sorry, this isn't quite right and needs more investigation.

**Comment by Fullaxx** [comment]
Apparently the unused return value is not the root cause.
It seems that when test_qtreetbl.c is compiled with -O2 the drawtree() will produce a segfault,
When I remove the -O2 optimizations flag to get better debugging symbols, drawtree() functions normally.
Commenting out the drawtree() does avoid the segfault, but I don't have a good explanation as to the root cause.
If anyone has any insight here, that would be greatly appreciated.

**Comment by wolkykim** [comment]
Hi Thanks for the report.
This is addressed by #95

**Comment by Fullaxx** [comment]
awesome, thanks! verified that works with gcc-12
